apiVersion: v1
kind: Pod
metadata:
  name: with-bad-digest
  namespace: apps
spec:
  containers:
    - args:
        - sleep
        - "3600"
      image: gallegit/hello-world:digest_mismatch
      name: lifespan-bad-digest
  restartPolicy: Always
