apiVersion: v1
kind: Pod
metadata:
  name: hello-world-app
  namespace: apps
spec:
  containers:
    - args:
        - sleep
        - "3600"
      image: gallegit/hello-world:latest
      name: hello-world-app
  restartPolicy: Always
