apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "legit-security.acme.com"
webhooks:
  - name: "legit-security.acme.com"
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: default
        name: legit-security
        path: /validate-pods
        port: 443
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJBQ0NRREhwU3RrcUFvZlNEQU5CZ2tx
        aGtpRzl3MEJBUXNGQURBbU1Rc3dDUVlEVlFRR0V3SkIKVlRFWE1CVUdBMVVFQXd3T2JHVm5hWFF0YzJW
        amRYSnBkSGt3SGhjTk1qSXdPVEV4TURZeU9UVXpXaGNOTWpNdwpPVEV4TURZeU9UVXpXakFtTVFzd0NR
        WURWUVFHRXdKQlZURVhNQlVHQTFVRUF3d09iR1ZuYVhRdGMyVmpkWEpwCmRIa3dnZ0VpTUEwR0NTcUdT
        SWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDc3NHSXNsb1VTREd3NVRBa3AKVmc1d001QUM1YzZj
        UlRRajBNcVZ5THArdm1oTUNxbHFRbzR3ckJ3TVUzNFZLcXRtcjZRTWFOV1hpUG5hRmY2WAp3UWd1bndG
        VXBZYVdXR0pKNVlNQUFNd2lmSGl2ZGZkOVZ6OXVKSzFJeHRXa1NsbzRkSmt1ZEJ6MzV5eUc5NUVuCjh1
        QWwrSjBLSWd1VFRnd0RObHpEejExRExSQkpLcnVSTjlEdnh5a0lTZ1plMWNIUEpkc09PQ1FTU3JUdy9w
        cncKcFdPRFVBdUI1UHNzOWoyZ0pQSE9wVHNRTzhweXR4cnlheW1IMlVic1FvM3FpaXpkNkloNlc1R0dK
        eVNmNHlURQpXYnJLK3N5aHR3NGtINnVtdFJrTjdaaHRqQU51MWg3SFNHMHV0RE5pdzNhK1VhSmhUNzJJ
        Y3F4cjk0WkNsclJSCmlJeXpBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFLbVBxYy81NzNy
        Qld5d1BLNFRCaThPRXkyR0MKbldaZ2drOFQ1L0NWenA1RXBMWlNaVWpMUENhaUJjZWhONFpnS1V2QnJv
        aXA1MGIwNzJPMkJ6MHpSWGtzVFBEcwpHNFFrcXhKMS9RQnlYOVlHcDFSdGdKbURRWEpmZTRLZHV1ZWlC
        cnVOY3JObjlmSVNLaWtWYTd1TGVUSGVLaGdKCk9XVmg3R1pPV2tMYzh3SG5id0hrRDZQOFJIaUcrVnlQ
        TE9RZUhPVkRPMVcrMDVPdFVGcFFPTzlrNDNGdWhKY2kKMFVsRFZFYzBybUhLMjhxUGJHK1lhN3ZrNXpD
        T0FjdVM2UDJNRDluYVpXaFRkQ2dnejVxd2FRZFlRekJtUXBIQwpKSng0M3FpUU0yRFRxSWp0L2ZZT0dh
        YWN3SkUrUk9Ob09vYkxDMHYrVGZWbzF2bllMa2c1MmtGdHpHaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUt
        LS0tLQo=
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2
